// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY'),
    appId: '1:725673907364:web:422760af871da48aff8231',
    messagingSenderId: '725673907364',
    projectId: 'app4-tree',
    authDomain: 'app4-tree.firebaseapp.com',
    storageBucket: 'app4-tree.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
    appId: '1:725673907364:android:65aa5033d35b12bcff8231',
    messagingSenderId: '725673907364',
    projectId: 'app4-tree',
    storageBucket: 'app4-tree.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    appId: '1:725673907364:ios:3ffecafd696b4f5eff8231',
    messagingSenderId: '725673907364',
    projectId: 'app4-tree',
    storageBucket: 'app4-tree.firebasestorage.app',
    iosBundleId: 'com.example.app4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    appId: '1:725673907364:ios:3ffecafd696b4f5eff8231',
    messagingSenderId: '725673907364',
    projectId: 'app4-tree',
    storageBucket: 'app4-tree.firebasestorage.app',
    iosBundleId: 'com.example.app4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY'),
    appId: '1:725673907364:web:831f1aeabd9a2413ff8231',
    messagingSenderId: '725673907364',
    projectId: 'app4-tree',
    authDomain: 'app4-tree.firebaseapp.com',
    storageBucket: 'app4-tree.firebasestorage.app',
  );
}
